### Question 1 - 2

In [3]:
# Object Oriented Programming
import math
import torch


# Question 1
class Softmax:
    def __init__(self, data):
        self.data = data
    def softmax(self):
        result = []
        expx = []
        for i in self.data:
            expx.append(math.exp(i))
        for i in expx:
            result.append(i/sum(expx))
        return torch.tensor(result)
    def softmax_table(self):
        c = max(self.data)
        result = []
        expxc = []
        for i in self.data:
            expxc.append(math.exp(i - c))
        for i in expxc:
            result.append(round(i/sum(expxc), 4))
        return torch.tensor(result)
data = torch.tensor([1,2,3])
softmax = Softmax(data)
print(softmax.softmax())
print(softmax.softmax_table())

# Question 2

#a Cài đặt các class Student, Doctor, và Teacher theo mô tả trên. Thực hiện phương thức
# describe() method để in ra tất cả thông tin của các object.

class Student():
    def __init__(self, name, yob, grade, job="Student"):
        self.job = job
        self.grade = grade
        self.name = name
        self.yob = yob
    def describe(self):
        print(f'{self.job} - Name: {self.name} - YoB: {self.yob} - Grade: {self.grade}')

class Doctor():
    def __init__(self,name, yob, specialist, job="Doctor"):
        self.job = job
        self.specialist = specialist
        self.name = name
        self.yob = yob
    def describe(self):
        print(f'{self.job} - Name: {self.name} - YoB: {self.yob} - Specialist: {self.specialist}')

class Teacher():
    def __init__(self, name, yob, subject, job = 'Teacher'):
        self.job = job
        self.subject = subject
        self.name = name
        self.yob = yob
    def describe(self):
        print(f'{self.job} - Name: {self.name} - YoB: {self.yob} - Subject: {self.subject}')

student1 = Student(name="studentA", yob=2010, grade="7")
student1.describe()
teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher1.describe()
doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor1.describe()

"""
b Viết add_person(person) method trong Ward class để add thêm một người mới với nghề
nghiệp bất kỳ (student, teacher, doctor) vào danh sách người của ward. Tạo ra một ward
object, và thêm vào 1 student, 2 teacher, và 2 doctor. Thực hiện describe() method để in ra
tên ward (name) và toàn bộ thông tin của từng người trong ward.
"""

class Ward:
    def __init__(self, name):
        self.name = name
        self.ward_list = []
    def add_person(self, obj):
        self.ward_list.append(obj)
    def describe(self):
        print(f"Ward Name: {self.name}")
        for person in self.ward_list:
            person.describe()
    def count_doctor(self):
        count = 0
        for person in self.ward_list:
            if person.job.lower() == 'doctor':
                count += 1
        return count
    def sort_age(self):
        self.ward_list.sort(key=lambda x: x.yob)
        return self.ward_list
    def count_average_age(self):
        sum = 0
        count = 0
        for person in self.ward_list:
            if person.job.lower() == 'teacher':
                sum += person.yob
                count += 1
        return sum/count

ward1 = Ward(name = "Ward1")

student1 = Student(name="studentA", yob=2010, grade="7")
teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor2 = Doctor(name="doctorB", yob=1945, specialist="Endocrinologists")

ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(doctor1)
ward1.add_person(doctor2)

ward1.describe()

"""
c Viết count_doctor() method để đếm số lượng doctor trong ward.
"""
print(f"\nNumber of doctors: {ward1.count_doctor()}")

"""
d Viết sort_age() method để sort mọi người trong ward theo tuổi của họ với thứ tự tăng dần.
(hint: Có thể sử dụng sort của list hoặc viết thêm function đều được)
"""
print("\nSorted by age:")
ward1.sort_age()
ward1.describe()

"""
Viết compute_average() method để tính trung bình năm sinh của các teachers trong ward.
"""
print(f"\nAverage age of teachers: {ward1.count_average_age()}")



tensor([0.0900, 0.2447, 0.6652])
tensor([0.0900, 0.2447, 0.6652])
Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists
Ward Name: Ward1
Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists
Doctor - Name: doctorB - YoB: 1945 - Specialist: Endocrinologists

Number of doctors: 2

Sorted by age:
Ward Name: Ward1
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists
Doctor - Name: doctorB - YoB: 1945 - Specialist: Endocrinologists
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Student - Name: studentA - YoB: 2010 - Grade: 7

Average age of teachers: 1969.0


### Question 2

In [36]:
class Stack:
    def __init__(self, capacity):
        self.stack = []
        self.capacity = capacity

    def is_empty(self):
        return len(self.stack) == 0

    def is_full(self):
        return len(self.stack) == self.capacity

    def push(self, value):
        if self.is_full():
            print(f"Full stack {value}")
            return
        self.stack.append(value)

    def pop(self):
        if self.is_empty():
          print(f"Pop empty stack")
          return
        return self.stack.pop(-1)

    def top(self):
        if self.is_empty():
          print(f"Top empty stack")
          return
        return self.stack[-1]

In [37]:
stack1 = Stack(5)
stack1.is_empty()

True

In [38]:
stack1.push(1)
stack1.push(2)
stack1.push(3)
stack1.push(4)
stack1.push(5)
stack1.push(6)

Full stack 6


In [39]:
print(stack1.is_full())
print(stack1.top())

True
5


In [40]:
stack1.pop()
stack1.pop()
stack1.pop()
stack1.pop()
stack1.pop()
stack1.pop()

Pop empty stack


In [41]:
print(stack1.is_empty())
print(stack1.top())

True
Top empty stack
None


### Question 3

In [42]:
class Queue:
    def __init__(self, capacity):
        self.queue = []
        self.capacity = capacity

    def is_empty(self):
        return len(self.queue) == 0

    def is_full(self):
        return len(self.queue) == self.capacity

    def enqueue(self, value):
        if self.is_full():
          print("Enqueue to a full queue", value)
          return
        self.queue.append(value)

    def dequeue(self):
        if self.is_empty():
          print("Dequeue from an empty queue")
          return
        return self.queue.pop(0)

    def front(self):
        if self.is_empty():
          print("Front from an empty queue")
          return
        return self.queue[0]

In [43]:
queue1 = Queue(5)
queue1.is_empty()

True

In [44]:
queue1.enqueue(1)
queue1.enqueue(2)
queue1.enqueue(3)
queue1.enqueue(4)
queue1.enqueue(5)
queue1.enqueue(6)

Enqueue to a full queue 6


In [45]:
print(queue1.is_full())
print(queue1.front())

True
1


In [46]:
queue1.dequeue()
queue1.dequeue()
queue1.dequeue()
queue1.dequeue()
queue1.dequeue()
queue1.dequeue()

Dequeue from an empty queue


In [47]:
print(queue1.is_empty())
print(queue1.front())

True
Front from an empty queue
None


## Multiple Choices Question

### Q1

In [48]:
import torch
import torch.nn as nn

data = torch.Tensor([1, 2, 3])
softmax_function = nn.Softmax(dim =0)
output = softmax_function(data)
assert round(output[0].item(), 2) == 0.09
output
#C

tensor([0.0900, 0.2447, 0.6652])

### Q2

In [49]:
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        exp_x = torch.exp(x)
        sum_exp_x = torch.sum(exp_x, dim=-1, keepdim=True)
        return exp_x / sum_exp_x

data = torch.Tensor([5, 2, 4])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round(output[-1].item(), 2) == 0.26
output
#B

tensor([0.7054, 0.0351, 0.2595])

### Q3

In [50]:
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_exp = torch.exp(x)
        partition = x_exp.sum(0, keepdims=True)
        return x_exp / partition

data = torch.Tensor([1, 2, 300000000])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round(output[0].item(), 2) == 0.0
output
#C

tensor([0., 0., nan])

### Q4

In [51]:
import torch
import torch.nn as nn

class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x, dim=0, keepdims=True)
        x_exp = torch.exp(x - x_max.values)
        partition = x_exp.sum(0, keepdims=True)
        return x_exp / partition

data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
assert round(output[-1].item(), 2) == 0.67
output
#B

tensor([0.0900, 0.2447, 0.6652])

### Q5

In [52]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name:str, yob:int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Student(Person):
    def __init__(self, name:str, yob:int, grade:str):
        self._name = name
        self._yob = yob
        self._grade = grade

    def describe(self):
        return f'Student - Name: {self._name} - Yob: {self._yob} - Grade: {self._grade}'

student1 = Student(name='studentZ2023', yob=2011, grade='6')
assert student1._yob == 2011
student1.describe()
#A

'Student - Name: studentZ2023 - Yob: 2011 - Grade: 6'

### Q6

In [53]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name:str, yob:int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Teacher(Person):
    def __init__(self, name:str, yob:int, subject:str):
        self._name = name
        self._yob = yob
        self._subject = subject

    def describe(self):
        return f'Teacher - Name: {self._name} - Yob: {self._yob} - Subject: {self._subject}'

teacher1 = Teacher(name='teacherZ2023', yob=1991, subject='History')
assert teacher1._yob == 1991
teacher1.describe()
#B

'Teacher - Name: teacherZ2023 - Yob: 1991 - Subject: History'

### Q7

In [54]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name:str, yob:int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Doctor(Person):
    def __init__(self, name:str, yob:int, specialist:str):
        self._name = name
        self._yob = yob
        self._specialist = specialist

    def describe(self):
        return f'Doctor - Name: {self._name} - Yob: {self._yob} - Subject: {self._specialist}'

doctor1 = Doctor(name='doctorZ2023', yob=1981, specialist='Endocrinologists')
assert doctor1._yob == 1981
doctor1.describe()
#A

'Doctor - Name: doctorZ2023 - Yob: 1981 - Subject: Endocrinologists'

### Q8

In [55]:
class Ward:
    def __init__(self, name:str):
        self.__name = name
        self.__listPeople = []

    def add_person(self, person:Person):
        self.__listPeople.append(person)

    def describe(self):
        print(f'Ward Name: {self.__name}')
        for p in self.__listPeople:
            p.describe()

    def count_doctor(self):
        return sum(1 for person in self.__listPeople if isinstance(person, Doctor))

student1 = Student(name='studentA', yob=2010, grade='7')
teacher1 = Teacher(name='teacherA', yob=1969, subject="Math")
teacher2 = Teacher(name='teacherB', yob=1995, subject="History")
doctor1 = Doctor(name='doctorA', yob=1945, specialist="Endocrinologists")
doctor2 = Doctor(name='doctorB', yob=1975, specialist="Cardiologists")
ward1 = Ward(name="Ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.count_doctor()
#C

2

### Q9

In [56]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def push(self, value):
        if self.is_full():
            raise OverflowError('Push full stack')
        self.__stack.append(value)

stack1 = MyStack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.is_full())
#B

False


### Q10

In [57]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def push(self, value):
        if self.is_full():
            raise OverflowError('Push to a full stack')
        self.__stack.append(value)

    def is_empty(self):
        return len(self.__stack) == 0

    def pop(self):
        if self.is_empty():
            raise IndexError('Pop from an empty stack')
        return self.__stack.pop(-1)

    def top(self):
        if self.is_empty():
            raise IndexError('Top from an empty stack')
        return self.__stack[-1]

stack1 = MyStack(capacity =5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.top())
#B

2


### Q11

In [58]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def enqueue(self, value):
        if self.is_full():
            raise OverflowError("Enqueue to a full queue")
        self.__queue.append(value)

queue1 = MyQueue(capacity =5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.is_full())
#A

False


### Q12

In [60]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def enqueue(self, value):
        if self.is_full():
            raise OverflowError("Enqueue to a full queue")
        self.__queue.append(value)

    def is_empty(self):
        return len(self.__queue) == 0

    def dequeue(self):
        if self.is_empty():
            raise IndexError("Dequeue from an empty queue")
        return self.__queue.pop(0)

    def front(self):
        if self.is_empty():
            raise IndexError("Front from an empty queue")
        return self.__queue[0]

queue1 = MyQueue(capacity =5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print("Result",queue1.front())
#D

Result 1
